SELECT * FROM cdw_sapp_branch;

SELECT * FROM cdw_sapp_credit_card;

SELECT * FROM cdw_sapp_customer;

SHOW PROCESSLIST;
KILL 182;

SELECT cc.TIMEID, cc.TRANSACTION_VALUE, cc.TRANSACTION_TYPE, cc.CUST_CC_NO, 
c.FIRST_NAME, c.LAST_NAME,  cc.BRANCH_CODE, cc.TRANSACTION_ID 
FROM cdw_sapp_credit_card cc 
INNER JOIN cdw_sapp_customer c ON cc.CUST_SSN = c.SSN
WHERE c.CUST_ZIP = 17201 AND cc.TIMEID LIKE '____12%'
ORDER BY cc.TIMEID DESC;

SELECT TRANSACTION_TYPE, count(TRANSACTION_TYPE), sum(TRANSACTION_VALUE)
FROM cdw_sapp_credit_card
GROUP BY TRANSACTION_TYPE
ORDER BY TRANSACTION_TYPE;

SELECT cc.TIMEID, cc.TRANSACTION_VALUE, cc.CUST_CC_NO, 
c.FIRST_NAME, c.LAST_NAME,  cc.BRANCH_CODE, cc.TRANSACTION_ID 
FROM cdw_sapp_credit_card cc 
INNER JOIN cdw_sapp_customer c ON cc.CUST_SSN = c.SSN
WHERE cc.TRANSACTION_TYPE = 'Bills'
ORDER BY cc.TIMEID DESC;

SELECT b.BRANCH_STATE, sum(c.TRANSACTION_VALUE), count(c.TRANSACTION_VALUE)  
FROM cdw_sapp_branch b 
JOIN cdw_sapp_credit_card c USING (BRANCH_CODE)
WHERE b.BRANCH_STATE = "NY"
GROUP BY b.BRANCH_STATE;

SELECT * 
FROM cdw_sapp_customer
WHERE CUST_ZIP = 11803;

UPDATE cdw_sapp_customer
SET SSN = 122222222, LAST_UPDATED = CURRENT_TIMESTAMP
WHERE SSN = 123451068;


SELECT FIRST_NAME, MIDDLE_NAME, LAST_NAME, Credit_card_no, FULL_STREET_ADDRESS, 
CUST_CITY, CUST_STATE, CUST_ZIP, CUST_COUNTRY, CUST_PHONE, CUST_EMAIL
FROM cdw_sapp_customer
WHERE Credit_card_no = 4210653316827505;

SELECT TRANSACTION_ID, TIMEID, TRANSACTION_TYPE, TRANSACTION_VALUE 
FROM cdw_sapp_credit_card  
WHERE CUST_CC_NO = 4210653316827505 AND TIMEID LIKE '____12%'
ORDER BY TIMEID DESC;

SELECT TRANSACTION_ID, TIMEID, TRANSACTION_TYPE, TRANSACTION_VALUE 
FROM cdw_sapp_credit_card  
WHERE CUST_CC_NO = 4210653316827505 AND TIMEID BETWEEN 20180014 AND 20180715
ORDER BY TIMEID DESC;

SELECT SUBSTRING(TIMEID,5,2) AS mon, TRANSACTION_TYPE, count(TRANSACTION_TYPE)
FROM cdw_sapp_credit_card
GROUP BY mon, TRANSACTION_TYPE
ORDER BY mon;

SELECT SUBSTRING(TIMEID,5,2) AS mon,
	SUM(TRANSACTION_TYPE = "Bills") AS Bills,
    SUM(TRANSACTION_TYPE = "Education") AS Education,
    SUM(TRANSACTION_TYPE = "Entertainment") AS Entertainment,
    SUM(TRANSACTION_TYPE = "Gas") AS Gas,
    SUM(TRANSACTION_TYPE = "Grocery") AS Grocery,
    SUM(TRANSACTION_TYPE = "Healthcare") AS Healthcare,
    SUM(TRANSACTION_TYPE = "Test") AS Test
FROM cdw_sapp_credit_card
WHERE TIMEID BETWEEN "201803%" AND "201808%"
GROUP BY mon
ORDER BY mon;

SELECT CUST_STATE, COUNT(CUST_STATE) as Count 
FROM cdw_sapp_customer
GROUP BY CUST_STATE
ORDER BY Count DESC;

SELECT CUST_SSN, count(TRANSACTION_VALUE) as qty
FROM cdw_sapp_credit_card
GROUP BY CUST_SSN
ORDER BY qty DESC
LIMIT 10;

SELECT CUST_SSN as SSN,sum(TRANSACTION_VALUE) as Total
FROM cdw_sapp_credit_card
GROUP BY CUST_SSN
ORDER BY Total DESC
LIMIT 10;

SELECT Application_Status 
FROM cdw_sapp_loan_application
WHERE Self_employed = "Yes";