SELECT * FROM cdw_sapp_branch;

SELECT * FROM cdw_sapp_credit_card;

SELECT * FROM cdw_sapp_customer;



SELECT cc.TIMEID, cc.TRANSACTION_VALUE, cc.TRANSACTION_TYPE, cc.CUST_CC_NO, 
c.FIRST_NAME, c.LAST_NAME,  cc.BRANCH_CODE, cc.TRANSACTION_ID 
FROM cdw_sapp_credit_card cc 
INNER JOIN cdw_sapp_customer c ON cc.CUST_SSN = c.SSN
WHERE c.CUST_ZIP = 17201 AND cc.TIMEID LIKE '____12%'
ORDER BY cc.TIMEID DESC;

SELECT TRANSACTION_TYPE, count(TRANSACTION_TYPE), sum(TRANSACTION_VALUE)
FROM cdw_sapp_credit_card
GROUP BY TRANSACTION_TYPE
ORDER BY TRANSACTION_TYPE;

SELECT cc.TIMEID, cc.TRANSACTION_VALUE, cc.CUST_CC_NO, 
c.FIRST_NAME, c.LAST_NAME,  cc.BRANCH_CODE, cc.TRANSACTION_ID 
FROM cdw_sapp_credit_card cc 
INNER JOIN cdw_sapp_customer c ON cc.CUST_SSN = c.SSN
WHERE cc.TRANSACTION_TYPE = 'Bills'
ORDER BY cc.TIMEID DESC;

SELECT b.BRANCH_STATE, sum(c.TRANSACTION_VALUE), count(c.TRANSACTION_VALUE)  
FROM cdw_sapp_branch b 
JOIN cdw_sapp_credit_card c USING (BRANCH_CODE)
WHERE b.BRANCH_STATE = "NY"
GROUP BY b.BRANCH_STATE;

SELECT * 
FROM cdw_sapp_customer;
WHERE SSN = all;
